# https://www.bwtz-essen.de/Ueber_uns/Tumorzentrum/Westdeutsches_Tumorzentrum.php

TUMOR_TYPE_MAP = {
    "DCP01BASIS": "Magen-Darm Tumoren",
    "DCP01BASIS2": "Magen-Darm Tumoren",
    "DCP01BASIS3": "Magen-Darm Tumoren",
    "RLKTUMORBAS": "Lungen- und Thoraxtumoren",
    "RLKTUMORBAS2": "Lungen- und Thoraxtumoren",
    "RLKTUMORBAS3": "Lungen- und Thoraxtumoren",
    "DCP03BASIS": "Leukämien, Lymphome und Myelome",
    "DCP03BASIS2": "Leukämien, Lymphome und Myelome",
    "DCP03BASIS3": "Leukämien, Lymphome und Myelome",
    "DCP04BASIS": "Gynäkologische Tumoren",
    "DCP04BASIS2": "Gynäkologische Tumoren",
    "DCP04BASIS2B": "Gynäkologische Tumoren",
    "DCP04BASISB": "Gynäkologische Tumoren",
    "DCP05BASIS": "Neuroonkologische Tumoren",
    "DCP05BASIS2": "Neuroonkologische Tumoren",
    "DCP06BASIS": "Tumoren der Harn- und Geschlechtsorgane",
    "DCP06BASIS2": "Tumoren der Harn- und Geschlechtsorgane",
    "DCP06BASIS3": "Tumoren der Harn- und Geschlechtsorgane",
    "DCP07BASIS": "Pädiatrische Hämatologie/Onkologie",
    "DCP07BASIS2": "Pädiatrische Hämatologie/Onkologie",
    "DCP08BASIS": "Hauttumoren",
    "DCP08BASIS2": "Hauttumoren",
    "DCP08BASIS3": "Hauttumoren",
    "DCP09BASIS": "Endokrine Tumoren",
    "DCP09BASIS2": "Endokrine Tumoren",
    "DCP10BASIS": "Kopf-Hals-Tumoren",
    "DCP10BASIS2": "Kopf-Hals-Tumoren",
    "DCP10BASIS3": "Kopf-Hals-Tumoren",
    "DCP10BASIS4": "Kopf-Hals-Tumoren",
    "DCP11BASIS": "Augentumoren",
    "DCP11BASIS2": "Augentumoren",
    "DCP12BASIS": "Knochen- und Weichteiltumoren (Sarkome)",
    "DCP12BASIS2": "Knochen- und Weichteiltumoren (Sarkome)",
    "DCP14BASIS": "Lebertumoren",
    "DCP14BASIS2": "Lebertumoren",
}
