version: '2.3' # nvidia-docker2 requires version 2.3 in order to be able to specify the container runtime

services:
  trainer:
    build:
      context: .
      dockerfile: "Dockerfile"
    user: $DOCKER_USER:$DOCKER_GROUP
    image: "ship-ai/fhirformer"
    runtime: nvidia
    shm_size: 32g
    ulimits:
      memlock: -1
      stack: 67108864
    environment:
      - FHIR_USER
      - FHIR_PASSWORD
      - SEARCH_URL
      - BASIC_AUTH
      - BASIC_AUTH_UME
      - REFRESH_AUTH
      - METRICS_USER
      - METRICS_PASSWORD
      - METRICS_HOSTNAME
      - METRICS_PORT
      - METRICS_DB
      - WANDB_API_KEY=$WANDB_API_KEY
      - WANDB_DIR=/app/wandb
      - WANDB_CACHE_DIR=/app/wandb
      - WANDB_CONFIG_DIR=/app/wandb
      - WANDB_DATA_DIR=/app/wandb
    volumes:
      - ./fhirformer:/app/fhirformer
      - ./wandb:/app/wandb
      - /raid/work/giubaldini/fhirformer:/data


networks:
  default:
    name: "fhirformer"
