# Defining params for FHIR-Extraction

###
# Training
##
# Run live pipline
is_live_prediction: False

# filter times for training data
start_datetime: '01-01-2017'
end_datetime: '01-01-2023'

#set root dir
root_dir: "/local/work/merengelke/icd_pred"

# Whether we should read the bundles from a cache folder, in case they have already been computed
read_from_fhir_cache: False
bundle_cache_folder_path: "./data_raw"

# Enforce to reload fhir resources
reload_cache: False
train_sample_path: 'train_samples.json'

# Patient
patient_path: './data_raw/patient.ftr'
patient_path_filtered: './data_filtered/patient.ftr'
patient_params: {
  '_count': 5000,
  '_sort': '-date'
}
patient_constraints: {'_id': 'patient_id'}

# Encounter
encounter_path: './data_raw/encounter.ftr'
encounter_path_filtered: './data_filtered/encounter.ftr'
encounter_params: {
  '_count': 1000,
  '_sort': '-date'
}
encounter_constraints: {'subject': 'patient_id'}

# BDP
bdp_path: './data_raw/bdp.ftr'
bdp_path_filtered: './data_filtered/bdp.ftr'
bdp_params: {
  'shipProductCode': 'TKZ,TKP',
  '_count': 1000,
  '_sort': '-shipStorageEnd',
  '_include': 'BiologicallyDerivedProduct:request'
}

# Observation
obs_path: './data_raw/obs.ftr'
obs_raw: './data_raw/obs_raw.ftr'
obs_path_filtered: './data_filtered/obs.ftr'
obs_params: {
  'code': 'zTHRA',
  '_count': 500,
  '_sort': '-date',
  '_include': 'Observation:based-on'
}

# Procedure
base_for_procedure: './patient.ftr'
procedure_path: './data_raw/procedure.ftr'
procedure_path_filtered: './data_filtered/procedure.ftr'
procedure_params: {
  '_count': 1000,
  '_sort': '-date'
}
procedure_constraints: {'subject': 'patient_id'}

# Condition
condition_path: './data_raw/condition.ftr'
condition_path_filtered: './data_filtered/condition.ftr'
condition_path_filtered_main_diag: './data_filtered/condition_main_diag.ftr'
condition_params: {
  '_count': 1000,
  '_sort': '-recorded-date'
}

# Medication
medication_path_raw: './data_raw/medication_raw.ftr'
medication_path: './data_raw/medication.ftr'
medication_merged_path: './data_raw/medication_merged.ftr'
medication_merged_path_filtered: './data_filtered/medication.ftr'
medication_params: {
  '_count': 1000,
  '_sort': '_lastUpdated'
}
medication_req_params: {
  '_count': 1000,
  '_sort': '_lastUpdated',
#  'identifier': 'https://uk-essen.de/HIS/BD/Cato/MedicationRequest%7C'
}
medication_admin_params: {
  '_count': 1000,
  '_sort': '_lastUpdated'
}


# Train Samples
sample_path: './samples.json'

# wandb
wandb_project_name: 'autopilot_global_7d'
bdp_filter: 'total_tkz'


