task: None
debug: True

# General params for setting the folders and the extraction
# start_datetime: "2018-01-01"
# end_datetime: "2024-01-01"
# run_id: "2018-2024-v1"

start_datetime: "2018-01-01"
end_datetime: "2018-02-02"
run_id: "2018-2018-01"

root_dir: "/data"
step: "all"
# Whether to use the pre-train workflow (split patients into pretrain and downstream sets)
use_pretrain_workflow: False
data_id: {
    "ds_readmission": "V1",
    "ds_image": "V2",
    "ds_icd": "V1",
    "pretrain_fhir": "V1",
    "pretrain_documents": "V1",
    "ds_insurance_type": "V1",
    "ds_mortality": "V1"
}

# Training params
use_roformer: False
batch_size: 16
num_train_epochs: 50
max_train_samples: null # 300000
max_test_samples: null # 300000
train_ratio: 0.8
learning_rate: {
  "default": 1e-5,
  "ds_icd": { "default": 1e-6, "severinsimmler/xlm-roberta-longformer-large-16384": 2e-5 },
  "ds_readmission": { "default": 1e-5 },
  "pretrain_fhir": { "default": 2e-7 },
}
weight_decay: {
  "default": 0,
  "ds_image": {"default": 0},
  "ds_readmission": {"default": 0, "bert-base-german-cased": 0.01},
  "pretrain_documents": {"default": 0},
}

load_from_file: False
truncation: "longest_first"
model_checkpoint: "ikim-uk-essen/geberta-base"

# Enforce run and not read cache
rerun_cache: False
skip_validation: False
download_documents: False


# Resources used for extraction and for training
# If there isn't a key for the chosen task, the default is used
resources_for_task: {
    "default": [
        "condition",
        "procedure",
        "imaging_study",
        "diagnostic_report",
        "biologically_derived_product",
        "observation",
        "episode_of_care",
        "medication",
        "service_request",
    ],
    "ds_image": [
        "condition",
        "procedure",
        "imaging_study",
        "diagnostic_report",
        "episode_of_care",
    ],
    "ds_icd": [
        "condition",
        "procedure",
    ],
    "pretrain_documents": [
        "diagnostic_report",
    ],
}

# Patient
patient_params: {
  "_count": 1000,
  # "_sort": "-date"
}
patient_constraints: {"_id": "patient_id"}

# Patient parents
patient_parent_params: {
  "_count": 5000,
}
patient_parent_constraints: {"link": "patient_id"}

# Encounter
encounter_params: {
  "_count": 1000,
  "_sort": "-date"
}
encounter_constraints: {"subject": "patient_id"}

# BDP
bdp_params: {
  "_count": 1000,
  "_sort": "-shipStorageEnd",
  "_include": "BiologicallyDerivedProduct:request"
}

# Observation
obs_params: {
  "_count": 5000,
  "_sort": "-date",
}

# Procedure
procedure_params: {
  "_count": 1000,
  "_sort": "-date"
}
procedure_constraints: {"subject": "patient_id"}

# Condition
condition_params: {
  "_count": 1000,
  "_sort": "-recorded-date"
}

# Imaging Study
imaging_study_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

# diagnostic_report
diagnostic_report_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}


# Medication
medication_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}
medication_req_params: {
  "_count": 1000,
  "_sort": "_lastUpdated",
#  "identifier": "https://uk-essen.de/HIS/BD/Cato/MedicationRequest%7C"
}
medication_admin_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

# ServiceRequest
service_request_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

# episode_of_care_params
episode_of_care_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

eval_accumulation_steps: 5

# folders to clear on each run
folders_to_clear: [""]

# Sampling
num_processes: 50
# Main column is always a datetime column
text_sampling_column_maps: {
    "condition": {
        "drop_duplicates": ["patient_id", "condition_id"],
        "main_col": "condition_date",
        "bracket_cols": ["icd_code", "icd_display", "icd_version"]
    },
    "procedure": {
        "drop_duplicates": ["patient_id", "procedure_id"],
        "main_col": "start",
        "bracket_cols": ["code", "display"]
    },
    "imaging_study": {
        "drop_duplicates": ["patient_id", "imaging_study_id"],
        "main_col": "started",
        "bracket_cols": ["description", "procedure_code"],
        "ds_image_bracket_cols": ["description", "modality_code", "procedure_code"]
    },
    "biologically_derived_product": {
        "main_col": "ausgabe_datetime",
        "bracket_cols": ["output_to_einskurz", "display"]
    },
    "observation": {
        "main_col": "effectivedatetime",
        "bracket_cols": ["display", "value_quantity", "value_unit"]
    },
    "service_request": {
        "main_col": "authored",
        "bracket_cols": ["code_display", "category_display"]
    },
    "medication": {
        "main_col": "datetime",
        "bracket_cols": ["medication", "status"]
    },
    "encounter": {
        "drop_duplicates": ["patient_id", "encounter_id"],
        "main_col": "start",
        "bracket_cols": [
                    "encounter_id", "original_patient_id", "kind", "status", "v3_act_code", "v3_act_code_display", "type_code", "type_display", "fachabteilungsschluessel_code", "fachabteilungsschluessel", "v3_ParticipantTypeCode_code", "v3_ParticipantTypeCode_display", "practitioner_id", "end", "aufnahmeanlass_code", "aufnahmeanlass_display"]
    },
    "episode_of_care": {
        "main_col": "start",
        "bracket_cols": [
          "cert", "primary_case", "primary_year", "first_diagnosis_date", "treatment_program",
        ]
    },
    "diagnostic_report": {
        "main_col": "date",
        "bracket_cols": ["category_display", "title"]
    }
}
