# Set task
task: None
debug: False

# General params for setting the folders and the extraction
start_datetime: '2018-01-01'
end_datetime: '2023-01-01'
run_id: "2018-2023-v1"

#start_datetime: "2021-03-01"
#end_datetime: "2021-03-30"
#run_id: "testing_30d"
root_dir: "/data"
step: "all"

# Training params
use_roformer: False
num_train_epochs: 250
max_train_samples: null # 300000
max_test_samples: null # 300000
learning_rate: {
  "default": 2e-5,
  "ds_icd": { "default": 1e-6 },
  "ds_readmission": { "default": 2e-5 },
  "pretrain_fhir": { "default": 2e-7 },
}
weight_decay: {
  "default": 0.01,
  "ds_image": {"default": 2e-6},
  "ds_readmission": {"default": 0.01, "bert-base-german-cased": 0},
  "pretrain_documents": {"default": 0},
}

load_from_file: False
truncation: "longest_first"
model_checkpoint: "bert-base-german-cased"

# Enforce run and not read cache
rerun_cache: False
skip_validation: False
download_documents: False


# Resources used for extraction and for training
# If there isn't a key for the chosen task, the default is used
resources_for_task: {
    "default": [
        "condition",
        "procedure",
        "imaging_study",
        "diagnostic_report",
        "biologically_derived_product",
        "observation",  # todo needs adaption to not only deal with lab values
        "episode_of_care",
        "service_request",
        "medication",
    ],
    "pretrain_documents": [
        "diagnostic_report",
    ],
}

# Patient
patient_params: {
  "_count": 1000,
  "_sort": "-date"
}
patient_constraints: {"_id": "patient_id"}

# Patient parents
patient_parent_params: {
  "_count": 5000,
}
patient_parent_constraints: {"link": "patient_id"}

# Encounter
encounter_params: {
  "_count": 1000,
  "_sort": "-date"
}
encounter_constraints: {"subject": "patient_id"}

# BDP
bdp_params: {
  "_count": 1000,
  "_sort": "-shipStorageEnd",
  "_include": "BiologicallyDerivedProduct:request"
}

# Observation
obs_params: {
  "code": "zTHRA",
  "_count": 500,
  "_sort": "-date",
  "_include": "Observation:based-on"
}

# Procedure
procedure_params: {
  "_count": 1000,
  "_sort": "-date"
}
procedure_constraints: {"subject": "patient_id"}

# Condition
condition_params: {
  "_count": 1000,
  "_sort": "-recorded-date"
}

# Medication
medication_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}
medication_req_params: {
  "_count": 1000,
  "_sort": "_lastUpdated",
#  "identifier": "https://uk-essen.de/HIS/BD/Cato/MedicationRequest%7C"
}
medication_admin_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

# ServiceRequest
service_request_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

eval_accumulation_steps: 5

# folders to clear on each run
folders_to_clear: [""]

# Sampling
num_processes: 30
# Main column is always a datetime column
text_sampling_column_maps: {
    "condition": {
        "drop_duplicates": ["patient_id", "condition_id"],
        "main_col": "condition_date",
        "bracket_cols": ["icd_code", "icd_display", "icd_version"]
    },
    "procedure": {
        "drop_duplicates": ["patient_id", "procedure_id"],
        "main_col": "start",
        "bracket_cols": ["code", "display"]
    },
    "imaging_study": {
        "drop_duplicates": ["patient_id", "imaging_study_id"],
        "main_col": "started",
        "bracket_cols": ["number_series", "number_instances", "description"],
        "ds_image_bracket_cols": ["number_series", "number_instances", "description", "procedure_code"]
    },
    "biologically_derived_product": {
        "main_col": "ausgabe_datetime",
        "bracket_cols": ["output_to_einskurz", "display"]
    },
    "observation": {
        "main_col": "effectivedatetime",
        "bracket_cols": ["display", "value_quantity", "value_unit"]
    },
    "service_request": {
        "main_col": "authored",
        "bracket_cols": ["code_display", "category_display"]
    },
    "medication": {
        "main_col": "datetime",
        "bracket_cols": ["medication", "status"]
    },
    "encounter": {
        "drop_duplicates": ["patient_id", "encounter_id"],
        "main_col": "start",
        "bracket_cols": [
          "encounter_id", "original_patient_id", "kind", "status", "v3_act_code", "v3_act_code_display", "type_code", "type_display", "fachabteilungsschluessel_code", "fachabteilungsschluessel", "v3_participanttypecode_code", "v3_participanttypecode_display", "practitioner_id", "end", "aufnahmeanlass_code", "aufnahmeanlass_display", "discharge_text", "discharge_place_code", "discharge_place_display"]
    },
    "episode_of_care": {
        "main_col": "start",
        "bracket_cols": [
          "cert", "primary_case", "primary_year", "first_diagnosis_date", "treatment_program",
        ]
    },
    "diagnostic_report": {
        "main_col": "date",
        "bracket_cols": ["category_display", "title"]
    }
}
