# Defining params for FHIR-Extraction

# Set pipeline type
task: None
# filter times for training data

start_datetime: "2018-01-01"
end_datetime: "2023-01-01"
run_id: "2018-2023-v1"

debug: False

root_dir: "/data"

# Enforce to reload fhir resources
rerun_cache: False
skip_validation: True
download_documents: False

# Patient
patient_params: {
  "_count": 1000,
  "_sort": "-date"
}
patient_constraints: {"_id": "patient_id"}

# Patient parents
patient_parent_params: {
  "_count": 5000,
}
patient_parent_constraints: {"link": "patient_id"}

# Encounter
encounter_params: {
  "_count": 1000,
  "_sort": "-date"
}
encounter_constraints: {"subject": "patient_id"}

# BDP
bdp_params: {
  "_count": 1000,
  "_sort": "-shipStorageEnd",
  "_include": "BiologicallyDerivedProduct:request"
}

# Observation
obs_params: {
  "code": "zTHRA",
  "_count": 500,
  "_sort": "-date",
  "_include": "Observation:based-on"
}

# Procedure
procedure_params: {
  "_count": 1000,
  "_sort": "-date"
}
procedure_constraints: {"subject": "patient_id"}

# Condition
condition_params: {
  "_count": 1000,
  "_sort": "-recorded-date"
}

# Medication
medication_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}
medication_req_params: {
  "_count": 1000,
  "_sort": "_lastUpdated",
#  "identifier": "https://uk-essen.de/HIS/BD/Cato/MedicationRequest%7C"
}
medication_admin_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

# ServiceRequest
service_request_params: {
  "_count": 1000,
  "_sort": "_lastUpdated"
}

eval_accumulation_steps: 5

# folders to clear on each run
folders_to_clear: [""]

# Sampling
# Main column is always a datetime column
text_sampling_column_maps: {
    "condition": {
        "drop_duplicates": ["patient_id", "condition_id"],
        "main_col": "condition_date",
        "bracket_cols": ["icd_code", "icd_display", "icd_version"]
    },
    "procedure": {
        "drop_duplicates": ["patient_id", "procedure_id"],
        "main_col": "start",
        "bracket_cols": ["code", "display"]
    },
    "imaging_study": {
        "drop_duplicates": ["patient_id", "imaging_study_id"],
        "main_col": "started",
        "bracket_cols": ["number_series", "number_instances", "description"],
        "ds_image_bracket_cols": ["number_series", "number_instances", "description", "procedure_code"]
    },
    "biologically_derived_product": {
        "main_col": "ausgabe_datetime",
        "bracket_cols": ["output_to_einskurz", "display"]
    },
    "observation": {
        "main_col": "effectivedatetime",
        "bracket_cols": ["display", "value_quantity", "value_unit"]
    },
    "service_request": {
        "main_col": "authored",
        "bracket_cols": ["code_display", "category_display"]
    },
    "medication": {
        "main_col": "datetime",
        "bracket_cols": ["medication", "status"]
    },
    "encounter": {
        "drop_duplicates": ["patient_id", "id"],
        "main_col": "start",
        "bracket_cols": [
          "id", "original_patient_id", "kind", "status", "v3_act_code", "v3_act_code_display", "type_code", "type_display", "fachabteilungsschluessel_code", "fachabteilungsschluessel", "v3_participanttypecode_code", "v3_participanttypecode_display", "practitioner_id", "end", "aufnahmeanlass_code", "aufnahmeanlass_display", "discharge_text", "discharge_place_code", "discharge_place_display"]
    },
    "episode_of_care": {
        "main_col": "start",
        "bracket_cols": [
          "cert", "primary_case", "primary_year", "first_diagnosis_date", "treatment_program",
        ]
    },
    "diagnostic_report": {
        "main_col": "date",
        "bracket_cols": ["category_display", "title"]
    }
}

resources_for_task: {
    "default": [
        "condition",
        "procedure",
        "imaging_study",
        "diagnostic_report",
        "biologically_derived_product",
        "observation",  # todo needs adaption to not only deal with lab values
        "episode_of_care",
        "service_request",
        "medication",
    ],
    "pretrain_documents": [
        "diagnostic_report",
    ],
}


# Training
load_from_file: False
