DEPARTMENT_BY_STATION: {
        "hematooncology":
            [
                "WTZ1",
                "WTZ2",
                "WTZ3",
                "WTZ4",
                "#WTZH",
                "#WTZI",
                "#WTZI5",
                "#WTZI5T",
                "#WTZI-H",
                "KMT1",
                "KMT2",
                "KMT3",
                "#KMT",
                "#KMTVT",
                "#KMTKO",
                "#MEDH",
                "#N-ONKO",
                "#SSA",
                "S1",
                "S2",
                "#S",
            ],
        "heart_thorax":
            [
                "HZ1",
                "HZ2",
                "HZ3",
                "HZ4",
                "HZ6",
                "HZA",
                "HZI1",
                "HZI2",
                "HZI5",
                "#TC",
                "HZ1-CPU",
                "H1",
                "H2",
                "#MEDK",
                "CIMC",
                "TC1I",
                "AG",
            ],
        "pediatrics": [
                "KIK",
                "KIK2",
                "KIK3",
                "KIK4",
                "KIK5",
                "KIK7",
                "KIK6",
                "K1IT",
                "KIAH",
                "K1",
                "KIANO",
                "#KIAH",
                "#KIAA",
                "#KIAD",
                "#KIAE",
                "#KIAG",
                "#KIAK",
                "#KIAM",
                "#KIAN",
                "#KIANO",
                "#KIAP",
                "KMT3/Kinder",
                "ZNA-KINDER",
                "#SPZ",
                "KIK4F",
                "PZ",
                "FS", #Säuglingszimmer
            ],
        #Allgemeinchirurgie
        "general_surgery":
            ["#AC", "#CHIRNOT-AC", "AC1I", "AC2", "AC34", "AC5", "AC1U"],
        # Angiology
        "angiology": ["#AG"],
        #Anästhesie(Intensivmedizin)
        "anesthesia": ["INTK", "ITII"],
        # Derma
        "dermatology": ["#HPSTD", "#HT", "#H"],
        #HNO
        "ent": ["#HNO", "O1", "O2", "O3", "O4", "O2O4"],
        # Emergency
        "emergency": ["#CHIRNOT", "ZNA-NORD", "ZNA-SUED"],
        #Gynäkologie
        "gynecology":
            ["F1", "F2", "F3", "#F2", "#F3", "#KREISS", "#FGE", "#FGY", "KRS"],
        #Innere Medizin
        "internal_med":
            [
                "GASTRO1",
                "M-INf2",
                "NEPHRO1",
                "#HKT",
                "#MDIA",
                "#MEDE",
                "#MEDE-S",
                "#MEDG",
                "#LTXGERK",
                "#MEDN",
                "#M-INF",
                "#M-INFDOL",
                "#M-INFWI",
                "#MP D-FALL",
                "#NTP",
                "#NTPEI",
                "#NTPJÜ",
                "#NTPKR",
                "#NTPWI",
                "#SPRE",
                "#SPRE-P",
                "#SPRG",
                "#SPRK",
                "ENDO1",
                "MDIA",
                "MDIA2",
                "M-INF",
                "M-INF2",
                "MIMC",
                "#MEDALLG",
                "M1",
                "M2A",
                "M2B",
                "M2C",
                "M2",
                "M3",
                "M4",
            ],
        # Nulear medicine
        "nuclear_med": ["#NUM", "NUM"],
        # Neurology
        "neurology":
            [
                "N1",
                "N2",
                "N3",
                "#N",
                "#CHIRNOT-NKL",
                "#N-RUECKENS",
                "#WKZ",
                "#WKZ1",
                "#WPE",
                "#WTZI2",
                "WTZI-M",
                "NEURO1",
                "NEURO2",
                "NEURO3",
            ],
        # Neurochirurgie
        "neurosurgery":
            ["NCIT", "NC1", "NC2", "NC3", "NC4", "#NC", "#CHIRNOT-NC"],
        # Ophthalmologie(Augen)
        "ophthalmology": ["#A1", "#AO", "#AR", "#AUGSEH", "A1", "A2", "A3"],
        # Urologie
        "urology": ["U1", "U2", "#U"],
        # Unfallchirurgie
        "trauma":
            [
                "UC1I",
                "UC2",
                "UCI",
                "UOC",
                "#CHIRNOT-UC",
                "#UC",
                "#OC",
                "#UCT",
                "UC3",
                "UC4",
            ],
        # Psychiatrie
        "psych":
            [
                "P1",
                "P2",
                "P3",
                "P4",
                "P5",
                "PKJP1",
                "PKJP2",
                "PKJP3",
                "PKJP4",
                "PKJP5",
                "PP1",
                "PP2",
                "PS1",
                "PS2",
                "PS2TK",
                "#PTKKJPEG",
                "PTKKJPMU",
                "PFO1A",
                "PFO1B",
                "PFO2A",
                "PFO2B",
                "PFO3A",
                "PFO3B",
                "PAP",
                "PGP",
                "PKOMF",
            ],

        # Josef Hospital
        "josef_clinic":
            [
                "J-2B",
                "J-2C",
                "J-3",
                "J-3A",
                "J-3B",
                "J-3C",
                "J-4",
                "J-4A",
                "J-4B",
                "J-5",
                "J-5A",
                "J-ACH",
                "J-AHNO",
                "J-AIM",
                "J-AIM-G",
                "J-AIM-PE",
                "J-AIM-R",
                "J-AIM-R-LA",
                "J-AORTHO",
                "J-APOZ",
                "J-AROE",
                "J-ASV-GIT",
                "J-AUF",
                "J-AZBM",
                "J-AZNA",
                "J-BALDY",
                "J-HNO-2",
                "J-INT",
                "J-OP",
                "J-ORTHO",
                "J-PERS",
                "J-ZNA",
                "P-AMB-ORHAS",
                "P-AMB-ORKAM",
                "P-S01",
            ],
        # ruhrlandklinik Hospitla
        "ruhr_clinc":
            [
                "R-A-CHI-A",
                "R-A-CHI-S",
                "R-A-HSA",
                "R-ANOT",
                "R-A-P-ALL-C",
                "R-A-P-ILD",
                "R-A-P-IP",
                "R-A-P-LUTX",
                "R-A-P-MUKO",
                "R-A-P-SLM",
                "R-A-P-UNI",
                "R-AWR",
                "R-ITS",
                "RLK-A-CHI-S",
                "RLK-A-HSA",
                "RLK-A-P-ILD",
                "RLK-A-P-IP",
                "RLK-A-P-LTX",
                "RLK-A-P-MUKO",
                "RLK-A-P-SLM",
                "RLK-A-P-UNI",
                "RLK-ITS",
                "RLK-OP",
                "RLK-PD",
                "RLK-S1",
                "RLK-S2",
                "RLK-S3",
                "RLK-S3A",
                "RLK-S3IP",
                "RLK-S3ONK",
                "RLK-S4",
                "RLK-S4LTX",
                "RLK-S5",
                "RLK-W1",
                "RLK-W1CF",
                "RLK-W2",
                "RLK-W3",
                "RLK-W4SL",
                "R-OP",
                "R-S1",
                "R-S2",
                "R-S3",
                "R-S4",
                "R-S5",
                "R-W1",
                "R-W2",
                "R-W3",
                "R-W4SL",
            ],
        # Sonstige ('ITII' = postop alle Fächer, COVID, ARDS, "INTK" = med intensiv, neuro?)
        "other": [ "#SCHMERZ", "#ZENLAB", "PD", "ITII", "INTK", '#RECMEHR' ],
    }
