run_cap: 50
method: bayes
metric:
  name: eval/loss
  goal: minimize
parameters:
  use_condition:
    values: [true, false]
  use_procedure:
    values: [true, false]
  use_diagnostic_report:
    values: [true, false]
  use_biologically_derived_product:
    values: [true, false]
  use_observation:
    values: [true, false]
  use_episode_of_care:
    values: [true, false]
  use_medication:
    values: [true, false]
  use_service_request:
    values: [true, false]

program: fhirformer
project: fhirformer_ds_v2
command:
  - python
  - "-m"
  - "fhirformer"
  - "--is_sweep"
  - "--step"
  - "sampling+train"
  - "--use_imaging_study"
  - "true"
  - "--task"
  - "ds_image"
  - ${args}
